// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs5_fr7o-YJYc2SEEcuZl1UxKZBCXMy9A',
    appId: '1:149991619253:android:a195d936a7ed345d0e5cfc',
    messagingSenderId: '149991619253',
    projectId: 'vibora-6c5d7',
    storageBucket: 'vibora-6c5d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACEranoXoTdeoCNH0w2OtG7Gty0MZCOeA',
    appId: '1:149991619253:ios:386d00957707ad6b0e5cfc',
    messagingSenderId: '149991619253',
    projectId: 'vibora-6c5d7',
    storageBucket: 'vibora-6c5d7.firebasestorage.app',
    androidClientId: '149991619253-clprih6rhe810uk2ba9as60dtngrtuto.apps.googleusercontent.com',
    iosClientId: '149991619253-c318kq4g6alq0bpurj4vc2qqmed9fd10.apps.googleusercontent.com',
    iosBundleId: 'com.eventconnect.eventConnect',
  );

}